#!/bin/bash

IMAGE=${1:-xdralex/coreml:latest}

JUPYTER_PORT=4004
TENSORBOARD_PORT=6006

WORK=/home/apollo

exec docker run --gpus all --shm-size=8192m --rm -u apollo -p $JUPYTER_PORT:$JUPYTER_PORT -p $TENSORBOARD_PORT:$TENSORBOARD_PORT -w $WORK -v "$PWD:$WORK" $IMAGE \
	jupyter-notebook \
	--NotebookApp.ip=0.0.0.0 --NotebookApp.port=$JUPYTER_PORT \
	--NotebookApp.password_required=False --NotebookApp.token='' \
	--NotebookApp.custom_display_url="http://localhost:$JUPYTER_PORT"
